Repository se2-carcassonne-team/websocketServer, pull requests merged in 2024-06, with the labels that each got.

#29 End of Game to forward Scoreboard
  src/main/java/at/aau/serg/websocketserver/controller/GameSessionController.java
  src/main/java/at/aau/serg/websocketserver/domain/dto/FinishedTurnDto.java
  src/main/java/at/aau/serg/websocketserver/domain/dto/ScoreboardDto.java
  src/test/java/at/aau/serg/websocketserver/TestDataUtil.java
  src/test/java/at/aau/serg/websocketserver/controller/GameSessionControllerIntegrationTest.java
Labels: enhancement, good first issue

#32 Scoreboard object introduced + forwarded during the game
  src/main/java/at/aau/serg/websocketserver/controller/GameSessionController.java
  src/main/java/at/aau/serg/websocketserver/domain/dto/ScoreboardDto.java
  src/test/java/at/aau/serg/websocketserver/TestDataUtil.java
  src/test/java/at/aau/serg/websocketserver/controller/GameSessionControllerIntegrationTest.java
Labels: enhancement, bugfix

#34 refactor: sonarcloud issues handled
  src/main/java/at/aau/serg/websocketserver/controller/GameLobbyController.java
  src/main/java/at/aau/serg/websocketserver/controller/GameSessionController.java
  src/main/java/at/aau/serg/websocketserver/controller/PlayerController.java
  src/main/java/at/aau/serg/websocketserver/domain/dto/FinishedTurnDto.java
  src/main/java/at/aau/serg/websocketserver/domain/entity/GameLobbyEntity.java
  src/main/java/at/aau/serg/websocketserver/domain/entity/TileDeckEntity.java
  src/main/java/at/aau/serg/websocketserver/domain/entity/repository/GameSessionEntityRepository.java
  src/main/java/at/aau/serg/websocketserver/messaging/dtos/OutputMessage.java
  src/main/java/at/aau/serg/websocketserver/messaging/dtos/StompMessage.java
  src/main/java/at/aau/serg/websocketserver/service/PlayerEntityService.java
  src/main/java/at/aau/serg/websocketserver/service/impl/PlayerEntityServiceImpl.java
  src/test/java/at/aau/serg/websocketserver/controller/GameLobbyControllerIntegrationTest.java
  src/test/java/at/aau/serg/websocketserver/controller/GameSessionControllerIntegrationTest.java
  src/test/java/at/aau/serg/websocketserver/controller/PlayerControllerIntegrationTest.java
  src/test/java/at/aau/serg/websocketserver/demo/WebSocketBrokerIntegrationTest.java
  src/test/java/at/aau/serg/websocketserver/demo/WebSocketHandlerIntegrationTest.java
  src/test/java/at/aau/serg/websocketserver/helper/HelperMethodsTests.java
  src/test/java/at/aau/serg/websocketserver/mapper/PlayerMapperTest.java
  src/test/java/at/aau/serg/websocketserver/repository/GameLobbyEntityRepositoryTest.java
  src/test/java/at/aau/serg/websocketserver/repository/PlayerEntityRepositoryTest.java
  src/test/java/at/aau/serg/websocketserver/service/TileDeckEntityServiceImplTest.java
  src/test/java/at/aau/serg/websocketserver/websocket/ClientDisconnectListenerIntegrationTest.java
Labels: refactor

#35 fix: player points reset to 0 (for consistency)
  src/main/java/at/aau/serg/websocketserver/service/impl/PlayerEntityServiceImpl.java
Labels: bugfix

#37 feature: accusing another player of cheating
  src/main/java/at/aau/serg/websocketserver/controller/CheatController.java
  src/main/java/at/aau/serg/websocketserver/service/CheatService.java
  src/main/java/at/aau/serg/websocketserver/service/impl/CheatServiceImpl.java
  src/test/java/at/aau/serg/websocketserver/TestDataUtil.java
  src/test/java/at/aau/serg/websocketserver/controller/CheatControllerIntegrationTest.java
Labels: enhancement
